# Generated by Django 4.2.5 on 2023-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectone",
            name="current_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectone",
            name="status_code",
            field=models.IntegerField(blank=True, null=200),
        ),
        migrations.AlterField(
            model_name="projectone",
            name="utc_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
